# docker-compose.override.yml
version: "3.7"
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    volumes:
      - ./src:/usr/src
    environment:
      - SERVER_PORT=8000
    ports:
      - 8000:8000
